target/arm/translate.c
Currently, does not seem to build for the ARM target, and probably also not aarch64, due to a copy-paste error:
```
../target/arm/translate.c: In function ‘op_s_rri_rot’:
../target/arm/translate.c:5543:40: error: ‘tmp2’ undeclared (first use in this function); did you mean ‘tmp1’?
5543 |       libafl_gen_cmp(s->pc_curr, tmp1, tmp2, MO_32);
|                                        ^~~~
|                                        tmp1
```
This seems to fix the build. However, I am not sure the current code makes sense, since it seems to be a comparison with a (possibly) rotated immediate value. Not sure there need to be cmplog hooks placed on that?
=> [WIP] Fix build for ARM target

accel/tcg/translate-all.c
Works:
```
../configure --as-shared-lib --target-list=x86_64-linux-user --disable-blobs --disable-bsd-user --disable-fdt
make -j
```
Doesn't works:
```
../configure --as-shared-lib --target-list=arm-linux-user --disable-blobs --disable-bsd-user --disable-fdt
make -j
```
=> Fixing libafl_add_backdoor input type for 32-bit targets

configure
Removing the wildcard for configuration flags, enabling QEMU meson flags. 
Problem:
`./configure --help` indicated that additional flags will be passed through to meson. `./configure --disable-tmp` should be handled by meson, but throws an error due to the wildcard in front of it in the configure file. Probably a merge issue as the QEMU vanilla repo does not have this wildcard.
=> Fixing wildcard in configure

linux-user/mips/cpu_loop.c
Added handler for LibAFL breakpoints on MIPS. Without this Qemu will crash if it encounters a breakpoint set by qemu-libafl-bridge
=> Add handler for LibAFL breakpoint on MIPS

softmmu/runstate.c
currently, if you build qemu as standalone, you won't be able to use gdb because it will exit after breakpoint. this will fix that.
=> fixing standalone gdb break exit

linux-user/elfload.c, linux-user/hexagon/cpu_loop.c, target/hexagon/cpu-param.h
This is the first part of a patch to support Qualcomm Hexagon architecture in LibAFL. The second part (with the changes to LibAFL repo) is on the way.
I'm not the biggest fan of the changes made to the .elf loader as they feel somewhat hacky, however at least the binary I was analyzing would not load without them.
=> Hexagon support

accel/tcg/cputlb.c, libafl_extras/syx-snapshot/syx-snapshot.c
It is still required to check whether the fix is enough to avoid wrong dirty page reports.
For now, the assert is ignored in release builds.
=> Fix wrong dirty address tracking for MMIO accesses. Assert is only triggered for debug builds.

accel/tcg/cputlb.c, include/exec/ramblock.h, libafl_extras/syx-misc.h, libafl_extras/syx-snapshot/device-save.c, libafl_extras/syx-snapshot/device-save.h, libafl_extras/syx-snapshot/syx-snapshot.c, libafl_extras/syx-snapshot/syx-snapshot.h, system/physmem.c
This major update of Syx Snapshots includes multiple changes:
- Most of the tables are now GHashtable instances
- Possibility to perform memory snapshot correctness checking (device checking is a WIP)
- Simplified API: A lot of useless code has been deleted.
- More callbacks to catch more dirty pages
TODO: 
- check if `syx_snapshot_dirty_list_add_tcg_target` is still relevant (for performance reasons).
- check why the condition on `MMU_DATA_STORE` provokes memory correctness checks to fail.
=> Syx Snapshot rework

libafl_extras/syx-snapshot/syx-snapshot.c
Check if snapshot is enabled before logging also in range version of dirty_list_add.
=> Fix of syx_snapshot_dirty_list_add_hostaddr_range

libafl_extras/exit.c, libafl_extras/exit.h, system/runstate.c
Added qemu internal exit reason.
It's used when QEMU exits on its own.
It can be used to catch QEMU guest crashes or exits due to signals.
=> Internal exit

libafl_extras/exit.c, libafl_extras/exit.h
Restored `libafl_qemu_trigger_breakpoint` symbol deleted in PR #30
=> restore `libafl_qemu_trigger_breakpoint` symbol

linux-user/syscall.c
In QEMU's code handling `clone`, when `clone` creates a new thread, it does some QEMU stuff, creates a conditional variable and spawns a new thread.
https://github.com/AFLplusplus/qemu-libafl-bridge/blob/99ea52d12369d0bd30717c57e65719a2644b7c68/linux-user/syscall.c#L6647-L6683
The thread fills the data that'll be `clone`'s return value, and trigger the conditional variable.
https://github.com/AFLplusplus/qemu-libafl-bridge/blob/99ea52d12369d0bd30717c57e65719a2644b7c68/linux-user/syscall.c#L6544-L6568
When the `clone`'s caller gets unlocked, the info soon gets out of scope.
Then if LibAFL hooks are called, it accesses the freed-then-reused stack memory which contains trash.
=> clone: fix stack use after scope

.github/workflows/build_and_test.yaml, accel/tcg/translator.c, include/tcg/tcg-op.h, libafl_extras/hook.c, libafl_extras/hook.h
Note we do not need to free constant tcg temps (they are ignored by  `tcg_temp_free_internal` anyway).
For information, they are being garbage collected in `la_bb_end`.
=> Add tcg_env to backdoor callback

cpu-target.c, gdbstub/gdbstub.c
GDB does not always relies on `gdb_num_core_regs` to read / write. 
Use qemu primitives instead to cover all cases.
=> Fix libafl_qemu_read_reg and libafl_qemu_write_reg

tcg/tcg-op-ldst.c
When using the new QEMU version, the read hooks sometimes returned invalid addresses like 0x1 or 0x1000.
For reference this commit in upstream QEMU is relevant, where the handling for addresses was adjusted: https://gitlab.com/qemu-project/qemu/-/commit/d5920b7280762d4d696bff87f50dbce453adef06
And in https://gitlab.com/qemu-project/qemu/-/commit/eb9d02f24b1ce877a60ffaf6cc1ecc8484740b37 we can see, that QEMU temporarily stores the address in a TCGTemp variable, because it can get corrupted by the operation via overlaps.
To mimic QEMUs behavior, we copied the `plugin_maybe_preserve_addr` function, and used it in the same places as QEMU also does for its memory plugin callbacks.
Note that we copied this and technically repeat the same code, but QEMU disables all those functions when the …
=> Fixed invalid addresses in read hooks

io/channel-buffer.c, libafl/syx-snapshot/device-save.c
Unset object to free memory space allocated (memory leak in fast snapshot implementation for libafl).
This PR fix the memory leak. 
An issue about it has been created on LibAFL
=> Unset object to free memory space allocated (memory leak)

linux-user/riscv/cpu_loop.c
This adds support for using LibAFL with RISCV in userspace.
We just added the same calls as found in the other `cpu_loop.c` implementations to the riscv one.
=> feat(riscv): add libafl support

accel/tcg/translate-all.c, include/libafl/hook.h
- fix sigsetjmp bug
- fix tcg buffer overflow bug due to wrong icount report.
- closer to original QEMU implementation to improve maintainability.
- use the right TB icount / size semantic
- report problems related errors during generation
=> Refactor and fix edge-related code generation

accel/tcg/cpu-exec.c, accel/tcg/translate-all.c, include/libafl/exit.h, libafl/exit.c, libafl/hooks/tcg/block.c, libafl/hooks/tcg/edge.c, libafl/syx-snapshot/syx-snapshot.c, subprojects/libvduse/meson.build
there is a bug in the edge generation for systemmode.
this does not fix it atm, just does not trigger the bug if no exec hook is set up for edges.
also adds a clean exit for timeout.
=> Early return from libafl edge generation if no exec hooks

.gitignore, linker_interceptor.py
for some reason the string format changes between distributions, it should work on ubuntu now
=> Fix RPATH regex for Ubuntu

include/libafl/hook.h, include/libafl/hooks/tcg/edge.h, include/libafl/tcg.h, libafl/hooks/tcg/backdoor.c, libafl/hooks/tcg/block.c, libafl/hooks/tcg/cmp.c, libafl/hooks/tcg/edge.c, libafl/hooks/tcg/instruction.c, libafl/hooks/tcg/read_write.c, target/i386/tcg/emit.c.inc, target/i386/tcg/translate.c, tcg/tcg.c
latest qemu update changed `tcg_gen_callN` signature
=> Fix helper function calls & support for new x86 decoder

include/libafl/user.h, libafl/user.c
This add the `libafl_get_initial_brk` API to fix LibAFL #2776
=> Companion patch for LibAFL #2776

accel/tcg/tcg-runtime.c, accel/tcg/tcg-runtime.h, accel/tcg/translator.c, include/libafl/exit.h, include/libafl/tcg.h, libafl/exit.c, libafl/hooks/tcg/block.c, libafl/hooks/tcg/edge.c, libafl/hooks/tcg/read_write.c, target/i386/tcg/translate.c
companion patch for [LibAFL#2801](https://github.com/AFLplusplus/LibAFL/pull/2801).
=> Nyx api support

libafl/cpu.c
now, some archs use gdb's xml file as reference to get the number of core registers.
=> Fix wrong number of registers

accel/kvm/kvm-accel-ops.c, gdbstub/system.c, include/libafl/system.h, include/sysemu/cpus.h, libafl/system.c
reserve hw breakpoints for LibAFL, using them with GDB will return a graceful error. So far they are implemented only for kvm.
=> Add systemmode hw_breakpoint libafl set/remove fns

linux-user/syscall.c
glibc now defines `struct sched_attr`, which makes compilation fail.  i applied a recent qemu patch to make it work until we merge to latest qemu version with the patch applied (it has not been merged on mainline yet afaik).
=> Fix build for latest version of glibc

accel/kvm/kvm-accel-ops.c
@rmalmain fixes wrong breakpoint address returned by `qemu.run()`
=> sync CPU state on kvm hw breakpoint

accel/tcg/translate-all.c, include/libafl/hook.h, include/libafl/hooks/tcg/backdoor.h, include/libafl/hooks/tcg/block.h, include/libafl/hooks/tcg/cmp.h, include/libafl/hooks/tcg/edge.h, include/libafl/hooks/tcg/read_write.h, libafl/hooks/tcg/backdoor.c, libafl/hooks/tcg/block.c, libafl/hooks/tcg/cmp.c, libafl/hooks/tcg/edge.c, libafl/hooks/tcg/instruction.c, libafl/hooks/tcg/read_write.c, target/i386/kvm/kvm.c
also, use more `typedef` for fn pointers for consistency/readability.
=> Rename gen symbols for compatibility with rust 2024

accel/tcg/tcg-accel-ops-mttcg.c, accel/tcg/tcg-accel-ops-rr.c, accel/tcg/translate-all.c, include/libafl/hook.h, include/libafl/hooks/tcg/backdoor.h, include/libafl/hooks/tcg/block.h, include/libafl/hooks/tcg/cmp.h, include/libafl/hooks/tcg/edge.h, include/libafl/hooks/tcg/read_write.h, libafl/exit.c, libafl/hooks/tcg/backdoor.c, libafl/hooks/tcg/block.c, libafl/hooks/tcg/cmp.c, libafl/hooks/tcg/edge.c, libafl/hooks/tcg/instruction.c, libafl/hooks/tcg/read_write.c, target/i386/kvm/kvm.c
In some cases qemu_main_loop() can exit before libafl_sync_exit_cpu() completes. This will case race between Rust code that restarts QEMU and vCPU thread that updates last_exit_reason. What I observed is
libafl_exit_signal_vm_start() from a new iteration cleared last_exit_reason.cpu before libafl_sync_exit_cpu() tried to access *last_exit_reason.cpu. This caused NULL pointer dereference.
Fix this by not setting cpu->exit in prepare_qemu_exit() and updating it only in rr_cpu_thread_fn(). This will ensure that qemu_main_loop() waits for vCPU thread to actually stop before returning control to Rust code.
=> afl-bridge: fix race between main thread and a vCPU thread

include/exec/page-protection.h, linux-user/elfload.c, linux-user/mmap.c
When running applications which make large (sparsely populated) address ranges (e.g. when using address sanitizer with LibAFL) the inability to exclude these regions from any core dump can result in very large files which fill the disk. A coredump is obvously very useful for performing a post-mortem when fuzzing.
Whilst the man pages state that madvise provides only a hint (and hence can be ignored), this patch adds support to handle MADV_DONTDUMP and set a corresponding flag in the page flags, thus allowing QEMU to exclude these regions from the core file.
=> Support madvise(MADV_DONTDUMP) when creating core dumps for qemu-user
